name: Pull Request

on:
  pull_request:

jobs:
  pack-microcluster-token-distributor:
    uses: canonical/microcluster-token-distributor-operator/.github/workflows/pack.yaml@main
    with:
      name: microcluster-token-distributor
      path: token-distributor
  pack-microovn:
    uses: canonical/microcluster-token-distributor-operator/.github/workflows/pack.yaml@main
    with:
      name: microovn
      path: microovn
  test:
    runs-on: ubuntu-latest
    needs:
      - pack-microcluster-token-distributor
      - pack-microovn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: microcluster-token-distributor
      - uses: actions/download-artifact@v4
        with:
          name: microovn
      - run: |
          # NOTE this here to demonstrate use of workflow,
          #      replace with actual tests.
          echo ${{ needs.pack-microcluster-token-distributor.outputs.charms }}
          for charm in ${{ needs.pack-microcluster-token-distributor.outputs.charms }}; do
            mkdir charm
            pushd charm
            unzip ../$charm
            popd
            rm -rf charm
          done
          echo ${{ needs.pack-microovn.outputs.charms }}
          for charm in ${{ needs.pack-microovn.outputs.charms }}; do
            mkdir charm
            pushd charm
            unzip ../$charm
            popd
            rm -rf charm
          done
